

# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

workspace 'App'



target 'App' do
    project 'App/App.xcodeproj'

end


target 'Login' do
    project 'Login/Login.xcodeproj'
end

target 'User' do
    project 'User/User.xcodeproj'
end

target 'Core' do
    project 'Core/Core.xcodeproj'
end

target 'DSModule' do
    project '../DSModule.xcodeproj'
end

